"""
Django settings for Venter project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p!63vi=_4)o5h8k0ep4uy2e6ou^k$9wels#e&&x=^^!=$xa21o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'Prediction',
    'Login.apps.LoginConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Venter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'CategoryPrediction/../Login/templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Venter.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3')
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
STATIC_ROOT = 'static'
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "/Login/static"),
]

LOGIN_REDIRECT_URL = 'home'

EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails")

# Data folder stores the data of all users
MEDIA_ROOT = os.path.join(BASE_DIR, "MEDIA/")

# Maximum size of file uploaded by user
# 12534336 B = 12 MB
MAX_UPLOAD_SIZE = "12534336"

DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000000

SPEAKUP_CATEGORY_LIST = ['Delay in delivery', 'Wrong charges/Over charge', 'Consumer extremely frustated',
                         'Porting issues', 'Wrong/Faulty product',
                         'Payment Gateway failure', 'Internet issues', 'ATM related', 'Bad experience', 'Bad food',
                         'Staff Behaviour', 'Refund issues',
                         'Wrong charges', 'No Signal/Unable to use']

ICMC_CATEGORY_LIST = ['Drainage chokes and blockages', 'Overflowing drains or manholes',
                      'Replacement of missing/damaged manholes covers', 'Sunken manhole',
                      'Cleaning of septic tank', 'Repairs to pipe sewers/main sewers', 'Odour (foul smell) from drains',
                      'Bad patches/potholes on roads', 'Repairs/re-surfacing of roads/footpaths',
                      'Removal of rank regulation on roads', 'Reinstatement of trenches',
                      'Unauthorised digging of road', 'Providing name plates to the road', 'Street lighting', 'Signals',
                      'Speed breakers', 'Permission for tree cutting', 'Trimming of branches',
                      'Unauthorised Stalls on Roads', 'Fallen Tree on road', 'Bad Patches', 'Dangerous tree', 'Manhole',
                      'Flooding spot / Crosscut', 'Street furniture', 'Divider / Media',
                      'Unauthorised construction in slum', 'Unauthorised repairs/renovations in slum',
                      'Delay in transfer case',
                      'Unauthorised extension/construction', 'Unauthorised commercial activity', 'Lega',
                      'Issue of Birth / Death Certificate', 'Unauthorised Food Selling / Preparation',
                      'Unauthorized Flour Mill', 'Incorrect assessment of property', 'Non-availability of bills',
                      'Property Annexture, Transfer of Property, No Dues certificate, etc',
                      'Receipt against Online payment', 'Requirement to Assess the property',
                      'Searching the property details in absence of SACNo',
                      'Wrong billing name & address OR Wrong name of assessee',
                      'Wrong outstanding OR Payment related complaint', 'Delay in refund', 'Contact List of Wards',
                      'Unauthorised construction/development',
                      'Unauthorised alteration/renovation of building, flat, tenement, etc.',
                      'Permission for temporary monsoon shed',
                      'Regularisation of balcony enclosures',
                      'Repairs permission for tolerated/censured unauthorised structures',
                      'Granting authority u/s 499 of MMC Act for carrying out essential repairs',
                      'Heavy leakage from ceiling', 'Change of user - Res to Commercial', 'Establishment - Superio',
                      'Maintenance of municipal property, schools, dispensaries, maternity home, gardens',
                      'Maintenance of electric pumps in municipal colonies',
                      'Protection of municipal play grounds/gardens',
                      'Providing for monsoon to municipal property to avoid leakage',
                      'Providing/repairing doors, windows of P.S. Blocks',
                      'Proper electric supply to municipal properties', 'Major repairs to municipal property',
                      'Minor repairs to municipal property',
                      'Unauthorised stalls on roads, footpath or SWD drain',
                      'Unauthorised banners/advertisement/boards on roads/footpath',
                      'Unauthorised storage of explosives',
                      'Trade without License', 'Unauthorized workshop or Garage', 'Storage and sale of plastic bags',
                      'Mosquito nuisance', 'Rat nuisance', 'Fogging', 'Nuisance due to white ants',
                      'Nuisance due to cockroaches', 'Unauthorised/uncovered water storage tanks',
                      'Short supply of water', 'Choke in main drain', 'Drinking Water not available',
                      'Toilet not cleaned', 'Door/Window/staircase etc. found broken.', 'No electricity supply',
                      'Lamp,tubelight etc. to be replaced', 'Furniture found broken in the classes.',
                      'Found encroachment in the school premise', 'No Teacher', 'No warning/alarm system',
                      'Overflow of waste material', 'Pan/Gutka hawker near school premises',
                      'Bad Quality of material given to student', 'Pension / Family Pension Not Started',
                      'Current Month Pension / FP Not Received', 'Arrears Of Pension / FP Not Received',
                      'Gratuity Not Received', 'Commutation Of Pension Not Received',
                      'Arrears Of Pension Benefits Due To Rev.', '', 'NCPF Not Received',
                      'Leave Encashment Not Received',
                      'Cleaning of water entrance', 'Cleaning of open SWD', 'Flooding during monsoon',
                      'Pre-monsoon works halted', 'Providing damaged/missing gratings manhole covers over SWD',
                      'Removal of silt from nalla/across culverts, etc.', 'Repair to damaged open SWD',
                      'Unauthorised Stalls and Huts on nallas', 'Raising of manhole (except in monsoon)',
                      'Garbage not lifted from co-authorised collection point', 'Garbage not lifted from house gully',
                      'Collection point not attended properly',
                      'Garbage not lifted from municipal market', 'Garbage lorry not reported for service',
                      'Garbage lorry not covered', 'Providing/removing/replacing dustbins',
                      'Removal of dead animals', 'Sweeping of road', 'Cleaning of P.S.C. block/channels',
                      'No attendance at public toilets', 'Removal of Debris', 'Silt to be lifted on road',
                      'Non attendant of Nuisance Detector', 'Lifting of Tree Cutting', 'Nuisance due to masala mills',
                      'Air pollution', 'Pollution due to chemical effluents',
                      'Unauthorised factory, workshop or garage', 'Pertaining to rent', 'Transfer of tenancy',
                      'Unauthorised construction on the Plot/Room', 'Unauthorised use of Room',
                      'Non-maintenance of Premises', 'Pending Transfer cases.',
                      'Unauthorised addition/alteration in the premises', 'Unauthorised materials/furniture found',
                      'Extension in the premises without permission', 'Slab fallen down.',
                      'Unauthorised shed on building in premises', 'Open beyond permissible hours',
                      'Running without licence',
                      'Non observance of Holidays', 'Not providing minimum wages', 'Shop open on weekly holiday',
                      'found staff working more than on muster', 'Employing children (below 14) in the org',
                      'Online Renewal Application', 'Municipal Land - Road / Footpath / Strom Water Drain',
                      'Municipal Plot', 'Municipal Colony / Slum', 'Hawkers',
                      'Private Land / Building / Society / Factories', 'Leaks in water lines', 'Burst water main',
                      'Contaminated water supply', 'Shortage of water supply',
                      'Unauthorised tapping of water connections', 'Unauthorised use of water-Change of User',
                      'Use of booster pump', 'Removal of water meters', 'Providing water by tankers',
                      'Water supply during non-supply hours', 'Leakage near meter',
                      'Overflow of overhead tank / suction tank', 'Non receipt of water bills', 'Establishment - Labou',
                      'Office Superintenden']

ICMC_HEADERS = ['complaint_sub_category_iid', 'parent_cat_name', 'category_parent_iid', 'civic_agency_name',
                'complaint_title',
                'complaint_user_iid', 'user_iid', 'user_full_name', 'complaint_mobile_number', 'complaint_ward_iid',
                'ward_name', 'complaint_location', 'complaint_address_1', 'complaint_latitude', 'complaint_longitude',
                'complaint_created', 'latest_comp_satus_id', 'latest_comp_status_name', 'complaint_description']

SPEAKUP_HEADERS = ['id', 'user_id', 'vendor_id', 'complaint_type', 'feedback_status', 'get_response', 'last_response',
                   'got_resolved', 'resolved_date', 'send_reminder', 'text', 'phone', 'alt_phone', 'email',
                   'alt_email', 'city', 'state', 'image', 'voice', 'at_time', 'reference_id', 'contacted_date',
                   'status', 'updated_at',
                   'created_at', 'category_one', 'category', 'category_two']
